title: "Kokopelli • Plant Medicine"
description: "Small-batch plant medicines. Message to purchase."
url: "https://kokopelli.ie"
baseurl: ""
markdown: kramdown
theme: null

brand_name: "Kokopelli.ie"

# Contact
whatsapp_e164: "353862717477"
instagram_url: "https://www.instagram.com/kokopelli_plant_medicine?utm_source=qr&igsh=ZWlkM2drcGtvOTVm"
# etsy_url: "https://etsy.com/shop/YourShop"

# Collections
collections:
  products:
    output: true
    permalink: /products/:name/
  category:
    output: true
    permalink: /category/:name/
    sort_by: "order"

# Defaults
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product
  - scope:
      path: ""
      type: "category"
    values:
      layout: category

# Build includes/excludes
exclude:
  - README.md
  - assets/css/
  - node_modules/
  - package.json
  - package-lock.json
  - .github/
  - .gitignore
  - .vscode/
  - .DS_Store
  - Thumbs.db
  - CNAME
  - LICENSE
  - .jekyll-cache/
  - vendor/
  - .bundle/
  - Makefile
  - Gulpfile.js
  - assets/

# Preserve files/folders in the destination directory when Jekyll cleans it
keep_files:
  - assets
