title: Kokopelli • Plant Medicine
description: Small-batch plant medicines. Message to purchase.
url: "https://kokopelli.ie"
baseurl: ""   # "" if using custom domain at root
markdown: kramdown
theme: null

brand_name: "Kokopelli.ie"

# contact
whatsapp_e164: "353862717477"
instagram_url: "https://www.instagram.com/kokopelli_plant_medicine?utm_source=qr&igsh=ZWlkM2drcGtvOTVm"
# etsy_url: "https://etsy.com/shop/YourShop"

# products as a collection (no plugins)
collections:
  products:
    output: true
    permalink: /products/:name/

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product

  # default for standalone root-level pages (like about.md)
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# build includes
exclude:
  - README.md
  - assets/css/
  - node_modules/
  - package.json
  - package-lock.json
  - .github/
  - .gitignore
  - .vscode/
  - .DS_Store
  - Thumbs.db
  - CNAME
  - LICENSE
  - .jekyll-cache/
  - vendor/
  - .bundle/
  - Makefile
  - Gulpfile.js
  - assets/

# Preserve files/folders in the destination directory when Jekyll cleans it
# This prevents our Gulp-written assets from being deleted on each rebuild
keep_files:
  - assets
