name: Build Jekyll

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Bundle install
        run: |
          mkdir -p vendor/bundle
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
        env:
          BUNDLE_GEMFILE: Gemfile

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci

      - name: Gulp build (Jekyll + assets)
        run: npm run build
        env:
          BUNDLE_GEMFILE: Gemfile
          JEKYLL_ENV: production

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site
          if-no-files-found: error
